class CategoriaPrivada {
  final String titulo;
  final List<String> subcategorias;
  final String imagePath;

  CategoriaPrivada({required this.titulo, required this.subcategorias, required this.imagePath});
}

final List<CategoriaPrivada> categoriasPrivadas = [
  CategoriaPrivada(
    titulo: 'Asistencia Social',
    subcategorias: [
      'Asilos, Orfelinatos',
      'Casas de Empeño',
      'Centros de Rehabilitación',
      'Centros de Protección',
      'Dormitorios Públicos',
      'Guarderías'
    ],
    imagePath: 'assets/privada/as.png',
  ),
  CategoriaPrivada(
    titulo: 'Comercios y Oficinas',
    subcategorias: [
      'AGENCIA AUTOMOTRIZ. Clase 4. Área de exhibición, ventas, taller, área de refacciones. Estructura de acero',
      'Centros de Abastos',
      'Centros Comerciales',
      'Centros de Exposiciones',
      'Edificios Comerciales y Oficinas',
      'Farmacias y Drogerías',
      'Ferreterías y Tlapalerías',
      'Joyerías',
      'Librerías',
      'Mercados',
      'Supermercados y Autoservicios',
      'Interiorismo Comercial',
      'TIENDA DEPARTAMENTAL. Clase 5. Estructura mixta (Concreto y acero)',
      'Tiendas Especializadas',
      'Locales Comerciales',
      'Stands',
      'TIENDA DE CONVENIENCIA. Clase 4. Estructura de concreto y cubierta con estructura de acero y tiendas de Abarrotes',
      'TIENDA DE AUTOSERVICIO. Estructura Metálica, estacionamiento superficial descubierto (Tienda de equipo de cómputo y papelería) Centros comerciales',
      'Centros de exposiciones (Áreas de exposición)',
      'EDIFICIO PARA OFICINAS. Clase 2 baja 4 niveles. Estructura de concreto, muros de block, losa reticular sin estacionamiento, 2 fachadas Edificios comerciales y oficinas',
      'EDIFICIO PARA OFICINAS. Clase 4 media 8 niveles. Estructura mixta, 2 fachadas con elevador y estacionamiento en planta baja parte del edificio',
      'EDIFICIO PARA OFICINAS. Clase 4 media 6 niveles. Estructura de concreto, elevador y estacionamiento. En planta baja',
      'Mercados (no incluye áreas de estacionamiento)',
      'Supermercados y autoservicios',
      'Centros de Abastos (Centros de Acopio o Distribución) (no incluye estacionamientos}',
      'Distribuidores de bebidas (no incluye estacionamientos ni patios de maniobras)'
    ],
    imagePath: 'assets/privada/co.png',
  ),
  CategoriaPrivada(
    titulo: 'Medios de Comunicación',
    subcategorias: [
      'Agencia de Noticias',
      'Centrales Telefónicas',
      'Centros de Internet',
      'Edificios de Correos',
      'Edificios de Telégrafos',
      'Estudios de Audio y Video',
      'Estudios de Cine',
      'Estudios de TV',
      'Paquetería y Envíos',
      'Prensa',
      'Radiodifusoras',
      'Torres de Líneas de Alta Tensión 115-440 kva',
      'Torres de Aerogeneradores Eléctricos',
      'Paneles de Generación Solar Eléctricos',
      'Sub Estaciones Eléctricas',
      'Torres de control aéreo',
      'Editoriales (Editora de libros, revistas o periódicos)',
      'Estudios de audio y video',
      'Salas de espera'
    ],
    imagePath: 'assets/privada/mc.png',
  ),
  CategoriaPrivada(
    titulo: 'Transporte',
    subcategorias: [
      'Aeropuertos',
      'Terminales Aéreas',
      'Hangares',
      'Torres de Control',
      'Obra Exterior',
      'Casetas de Peaje',
      'Centrales de Autobuses',
      'Estaciones de Ferrocarril',
      'Estaciones de Transporte Colectivo',
      'Instalaciones Portuarias',
      'Paraderos de Autobuses',
      'Talleres de Mantenimiento',
      'Taquillas y Salas de Espera',
      'Agencia de Noticias',
      'Centros de internet',
      'Paraderos de Autobuses',
      'Casetas de Peaje',
      'Paquetería y Envíos'
    ],
    imagePath: 'assets/privada/mt.png',
  ),
  CategoriaPrivada(
    titulo: 'Cultura',
    subcategorias: [
      'Auditorios',
      'Bibliotecas',
      'Casas de Cultura',
      'Centros de Arte',
      'Editoriales',
      'Galerías de Arte',
      'Monumentos',
      'Museos',
      'Pabellones Internacionales y Nacionales',
      'Salas de Concierto',
      'Talleres de Arte',
      'Teatros',
      'Bibliotecas',
      'Cinetecas',
      'Centros de difusión cultural',
      'Galerías de Arte',
      'Hemerotecas',
      'Salas de lectura'
    ],
    imagePath: 'assets/privada/cultura.png',
  ),
  CategoriaPrivada(
    titulo: 'Deportivas',
    subcategorias: [
      'Albercas Recreativas',
      'Boliche',
      'Canchas Descubiertas',
      'Clubes Deportivos',
      'Gimnasios y Canchas Cubiertas',
      'Clubes deportivos',
      'Campo de Golf',
      'Casa Club',
      'Campo de Tiro',
      'Unidades Deportivas',
      'Boliche'
    ],
    imagePath: 'assets/privada/deportivas.png',
  ),
  CategoriaPrivada(
    titulo: 'Educación y Ciencia',
    subcategorias: [
      'Academias',
      'Centros de Investigación',
      'Campus de Educación Superior',
      'Escuelas Preescolares',
      'Escuelas Primarias',
      'Escuelas Secundarias',
      'Escuelas Preparatorias',
      'Escuelas Vocacionales',
      'Escuelas Técnicas',
      'Escuelas de Educación Especial',
      'Escuelas de Educación Superior',
      'Internados',
      'Laboratorios',
      'Laboratorios de Enseñanza',
      'Normales',
      'Laboratorios de investigación',
      'Observatorios',
      'ESCUELA SUPERIOR. Calidad popular, estructura de concreto.',
      'ESCUELA SUPERIOR. Calidad privada',
      'Áreas deportivas',
      'Campus universitarios',
      'Escuelas de idiomas'
    ],
    imagePath: 'assets/privada/ec.png',
  ),
  CategoriaPrivada(
    titulo: 'Financieras y Bancarias',
    subcategorias: [
      'Bancos',
      'Casas de Bolsa',
      'Casas de Cambio',
      'Oficinas Centrales y Regionales',
      'Organizaciones Auxiliares',
      'Cajas populares'
    ],
    imagePath: 'assets/privada/fb.png',
  ),
  CategoriaPrivada(
    titulo: 'Gubernamentales',
    subcategorias: [
      'Archivos',
      'Edificios',
      'Obra Exterior',
      'Cuarteles Militares',
      'Oficinas Estatales',
      'Oficinas Federales',
      'Oficinas Municipales',
      'Palacios de Gobierno',
      'Sedes Judiciales',
      'Sedes Legislativas',
      'Juzgados',
      'Agencias del Ministerio Público',
      'Bases aéreas',
      'Cuarteles'
    ],
    imagePath: 'assets/privada/gubernamentales.png',
  ),
  CategoriaPrivada(
    titulo: 'Habitacionales',
    subcategorias: [
      'Vivienda de 60 a100 m²',
      'Pies de Casa (Vivienda Popular en 36 m²)',
      'Vivienda Unifamiliar Popular (Vivienda económica hasta 60 m²)',
      'Vivienda Unifamiliar Media (de 61 a 100 m²)',
      'Vivienda Unifamiliar Media (De 101 a 150 m²)',
      'Vivienda Unifamiliar Media (de 151 a 200 m²)',
      'Vivienda Unifamiliar Alta (De 201 a 300 m²)',
      'Residencias (Casas de Lujo 301 a 500 m²)',
      'Residencias (Casas de Lujo 501 m² en adelante)',
      'Edificio para Departamentos. Clase 2 baja 2 niveles interés social. Sala-comedor, cocina, un baño, 2 recamaras y patio de servicio',
      'Edificio para Departamentos. Clase 2 baja 4 niveles interés social. Sala-comedor, cocina, un baño, 2 recamaras, y patio de servicio',
      'Edificio para Departamentos. Clase 4 media 4 niveles, Sala-comedor, cocina, patio de servicio, 1 baño, y 2 recamaras. 4 fachadas, estructura de acero y muro de tabique',
      'Edificio para Departamentos Clase 5 media Alta 5 niveles en adelante. Sala-comedor, cocina, patio de servicio, 2 baños y 3 recamaras. Estacionamiento P.B. y elevador. estructura',
      'Edificio para Departamentos. Clase 5 media alta 7 niveles. 2 fachadas. Sala-comedor, cocina, patio de servicio, 2 baños y 3 recamaras. Estacionamiento 2 sótanos y elevador.',
      'Edificio para Departamentos interés social más 4 de niveles',
      'Edificio para Departamentos medio residencial de más de 5 niveles',
      'Edificio para Departamentos residencial de lujo de más de 7 niveles'
    ],
    imagePath: 'assets/privada/habitacionales.png',
  ),
  CategoriaPrivada(
    titulo: 'Plantas Industriales',
    subcategorias: [
      'Áreas Exteriores',
      'Bodegas y Almacenes',
      'Laboratorios',
      'Talleres',
      'Áreas de empleados (comedor, baños)',
      'Laboratorios',
      'Plantas industriales completas (Maquiladoras) hasta 3,000 m²',
      'Plantas de artículos electrónicos hasta 3,000 m²',
      'Parques industriales hasta 5,000 m²',
      'Andenes',
      'Bodegas y almacenes hasta 1,600 m²',
      'Naves industriales Hasta 3,000 m²',
      'Talleres hasta 1.600 m²',
      'Industria ligera hasta 5,000 m²',
      'Industria mediana hasta 5,000 m²',
      'Industria pesada hasta 5,000 m²',
      'Industria ligera hasta 10,000 m²',
      'Industria mediana hasta 10,000 m²',
      'Industria pesada hasta 10,000 m²',
      'Industria ligera mas10,000 m²',
      'Industria mediana más 10,000 m²',
      'Industria pesada más 10,000 m²',
      'Oficinas',
      'Servicios del Personal',
      'Casetas de Seguridad Pública',
      'Edificios',
      'Obra Exterior',
      'Edificios',
      'Obra Exterior',
      'Cuarteles de Seguridad Pública',
      'Edificios',
      'Obra Exterior',
      'Edificios',
      'Obra Exterior',
      'Laboratorios Especializados',
      'SEMEFO\'s'
    ],
    imagePath: 'assets/privada/industriales.png',
  ),
  CategoriaPrivada(
    titulo: 'Recreación y Entretenimiento',
    subcategorias: [
      'Arenas Deportivas',
      'Autódromos',
      'Billares',
      'Centros Nocturnos',
      'Cines',
      'Estadios',
      'Hipódromo',
      'Jardines (zoológico, botánicos)',
      'Lienzos Charros',
      'Palenques',
      'Parques',
      'Planetarios',
      'Plazas Públicas',
      'Plazas de Toros',
      'Salones de Fiesta',
      'Edificios',
      'Obra exterior',
      'Teatros',
      'Auditorios',
      'Bares',
      'Video centros',
      'Video juegos',
      'Balnearios',
      'Parques Tecnológicos',
      'Salones de Fiesta',
      'Canchas Deportivas y áreas Lúdicas',
      'Casinos',
      'Altares',
      'Casas de retiro (espiritual)',
      'Oficinas administrativas',
      'Velatorios'
    ],
    imagePath: 'assets/privada/re.png',
  ),
  CategoriaPrivada(
    titulo: 'Religión',
    subcategorias: [
      'Basílicas y Catedrales',
      'Capillas',
      'Casas Pastorales',
      'Conventos y Monasterios',
      'Iglesias',
      'Sede Arzobispal'
    ],
    imagePath: 'assets/privada/religion.png',
  ),
  CategoriaPrivada(
    titulo: 'Salud',
    subcategorias: [
      'Centros de Rehabilitación Física',
      'Centros de Salud',
      'Dispensarios',
      'Laboratorio de Análisis Clínicos',
      'Laboratorio de Rayos X',
      'Hospitales',
      'Laboratorios Especializados',
      'Unidades de Servicio Médico',
      'Centros Antirrábicos',
      'Balnearios termales',
      'Clínicas',
      'Baños públicos',
      'Consultorios'
    ],
    imagePath: 'assets/privada/salud.png',
  ),
  CategoriaPrivada(
    titulo: 'Seguridad y Orden Público',
    subcategorias: [
      'Casetas',
      'Archivos',
      'Correccionales',
      'Laboratorios especializados',
      'Cárceles',
      'Centros de readaptación social',
      'Cuarteles',
      'Delegaciones (Policía, Tránsito o Bomberos)',
      'Departamentos de Tránsito',
      'Estaciones de bomberos',
      'Estaciones de policías',
      'Oficinas administrativas',
      'SEMEFO\'s'
    ],
    imagePath: 'assets/privada/sop.png',
  ),
  CategoriaPrivada(
    titulo: 'Turismo',
    subcategorias: [
      'Agencias de Viaje',
      'Edificios',
      'Obra Exterior',
      'Camping',
      'Centros de Convenciones',
      'Complejos Hoteleros',
      'Complejos y Hoteles (Obra Exterior)',
      'Hoteles de cinco estrellas',
      'Hoteles de cuatro estrellas',
      'Hoteles de tres estrellas o menos',
      'Moteles',
      'Trailer Park',
      'SPA\'s'
    ],
    imagePath: 'assets/privada/turismo.png',
  ),
  CategoriaPrivada(
    titulo: 'Alimentos y Bebidas',
    subcategorias: [
      'Bares y Cantinas',
      'Cafeterías',
      'Cocinas Rápidas',
      'Comedores',
      'Restaurantes'
    ],
    imagePath: 'assets/privada/ab.png',
  ),
  CategoriaPrivada(
    titulo: 'Varios',
    subcategorias: [
      'Baños Públicos',
      'Estacionamientos Descubiertos',
      'Estacionamientos Cubiertos',
      'Gasolineras'
    ],
    imagePath: 'assets/privada/varios.png',
  )
];